//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WanFang.BLL.WanfangWebService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WanfangWebService.ServiceSoap")]
    internal interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable UserInfo(string oper_id, string oper_psw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Patient", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Patient(string chr_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Costcenter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Costcenter();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TaskSend", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string TaskSend(string sys_type, string para_code, string oper_no, string from, string to, string urg_flag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TaskCancel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string TaskCancel(string sys_type, int task_no, string oper_no, string remark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendTime(string task_no, string para_code, string send_no, string send_time);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ArrLISTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ArrLISTime(string task_no, string para_code, string oper_no, string arr_time);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ScanBarcode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ScanBarcode(string task_no, string barcode_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeliverInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DeliverInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LabSche", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable LabSche(string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PatientFeeNo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string PatientFeeNo(string chr_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/web_cost_basic", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable web_cost_basic(string dept_type);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface ServiceSoapChannel : WanFang.BLL.WanfangWebService.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class ServiceSoapClient : System.ServiceModel.ClientBase<WanFang.BLL.WanfangWebService.ServiceSoap>, WanFang.BLL.WanfangWebService.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Data.DataTable UserInfo(string oper_id, string oper_psw) {
            return base.Channel.UserInfo(oper_id, oper_psw);
        }
        
        public System.Data.DataTable Patient(string chr_no) {
            return base.Channel.Patient(chr_no);
        }
        
        public System.Data.DataTable Costcenter() {
            return base.Channel.Costcenter();
        }
        
        public string TaskSend(string sys_type, string para_code, string oper_no, string from, string to, string urg_flag) {
            return base.Channel.TaskSend(sys_type, para_code, oper_no, from, to, urg_flag);
        }
        
        public string TaskCancel(string sys_type, int task_no, string oper_no, string remark) {
            return base.Channel.TaskCancel(sys_type, task_no, oper_no, remark);
        }
        
        public string SendTime(string task_no, string para_code, string send_no, string send_time) {
            return base.Channel.SendTime(task_no, para_code, send_no, send_time);
        }
        
        public string ArrLISTime(string task_no, string para_code, string oper_no, string arr_time) {
            return base.Channel.ArrLISTime(task_no, para_code, oper_no, arr_time);
        }
        
        public string ScanBarcode(string task_no, string barcode_no) {
            return base.Channel.ScanBarcode(task_no, barcode_no);
        }
        
        public string DeliverInfo() {
            return base.Channel.DeliverInfo();
        }
        
        public System.Data.DataTable LabSche(string date) {
            return base.Channel.LabSche(date);
        }
        
        public string PatientFeeNo(string chr_no) {
            return base.Channel.PatientFeeNo(chr_no);
        }
        
        public System.Data.DataTable web_cost_basic(string dept_type) {
            return base.Channel.web_cost_basic(dept_type);
        }
    }
}
